version: '3.9'

services:
  web:
    build: .
    container_name: exposaas_app
    restart: always
    ports:
      - "3000:3000"
   environment:
      NEXTAUTH_SECRET: "FleetHubSShamiDNDsol"
      DATABASE_URL="postgresql://postgres:0000@postgres:5432/exposaas?schema=public"
   depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: exposaas_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: exposaas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
