version: '3.9'

services:
  web:
    build: .
    container_name: exposaas
    restart: always
    ports:
      - "3001:3001"
      - "5000:5000"
    environment:
      NEXTAUTH_SECRET: "expoSAASDndDanish!2"
      DATABASE_URL: "postgresql://postgres:master@host.docker.internal:5432/exposaas?schema=public"
      AZURE_STORAGE_ACCOUNT_NAME: "dndsol"
      AZURE_STORAGE_ACCOUNT_KEY: "cUd5LDE/ulUlY+RMZbW4r0RoX3mQRHVPO50qSTHdjbXkF6KMrYVUzdbYA6+RKOLT6RDEPfMByMSr+AStPiywsw=="
      AZURE_STORAGE_CONTAINER_NAME: "exposaas"
      NEXT_PUBLIC_WS_URL: "wss://exposaas.dndsol.co/ws/"
      GEMINI_API_KEY: "AIzaSyDimtsYwBQV3uSRPiEkbgbA7HSeORkuKtg"
    extra_hosts:
      - "host.docker.internal:host-gateway"
